### PR TITLE
NEW: Azure connectivity

### PR DESCRIPTION
**Pull request by elliot-sawyer**
* Small tweaks to support SSL over Azure
* Update documentation for Azure Setup

### CODE REVIEW

**Comment by elliot-sawyer** [comment]
I've had positive feedback from @phptek and @tractorcow that this feature branch works well. If there are no objections I will merge it into master and release a new tag

**Comment by erikfrerejean** [comment]
We've been running this patch in production for close to a year now without any issues. Would be great to see a formal release with this update so we can stop running a non-stable branch :)

**Comment by elliot-sawyer** [comment]
Merged and tagged 1.0.0

**Comment by erikfrerejean** [comment]
Thanks!

**Pull request merged**
